# site settings
title: Painted Desert
subtitle: Rocks
email: desertpainted@gmail.com
description: We pray to the old and new gods of Rock and Metal. In their realm there is no best and no worst; there is only Music. We are mere acolytes, sharing our stories so they may live on through our listeners, carrying forward the eternal urge to rock.
url: "https://painteddesertrocks.github.io"
baseurl: ""     # keep empty for root
author:
street_address:
city: Steyr
state: OÖ
zip_code:
country: Austria
phone:
Formspree: movrezqa

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/painteddesertrocks
  GitLab:  painteddesertrocks
  Google-Plus: painteddesertrocks
  Instagram: painteddesertrocks
  LinkedIn: painteddesertrocks
  Twitter:
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
  - "*.gemspec"
  - LICENSE.md
  - CONTRIBUTING.md
  - README.md
  - node_modules
  - vendor
  - .github
  - Gemfile
  - Gemfile.lock

