# site settings
title: Painted Desert
subtitle: Rocks
email: desertpainted@gmail.com
description: We pray to the old and new gods of Rock and Metal - there is no best or worst - there is only Music. We are simple acolytes trying to share our story so they may be live through our listeners, carring forward the eternal urge to rock.
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address:
city: Steyr
state: OÖ
zip_code:
country: Austria
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/painteddesertrocks
  GitLab:
  Google-Plus:
  Instagram: rock_with_painted_desert
  LinkedIn:
  Twitter:
  Facebook:
  Slack:
  Youtube:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md
